Homework1
made-ml-in-prod-2021/rchermanteev pull request #2
Opened 2021-05-09 17:01 UTC by rchermanteev

Здравствуйте!

В домашней работе был сделан "production ready" проект для решения задачи классификации.
За основу были взяты [семинарские ](https://github.com/made-ml-in-prod-2021/ml_project_example) наработки. 
Данные для задачи классификации были взяты [тут](https://www.kaggle.com/ronitf/heart-disease-uci)
Работа выполнялась по пунктам из [поста](https://data.mail.ru/blog/topic/view/18519/) 
В README приведён чек-лист по пунктам, он же является самоанализом моей работы.

2021-05-10 21:47 UTC, KPOTOH commented on homework_1/data/raw/test.csv
> +age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
Гитхаб не для данных (даже в игрушечном примере)

2021-05-10 21:53 UTC, KPOTOH commented on homework_1/ml_project/features/build_features.py
> +    return target
Пробелы не по pep8

2021-05-10 21:59 UTC, KPOTOH commented on homework_1/ml_project/models/train_model.py
> +    return model
Гиперпараметры модели лучше записать в конфиг

2021-05-10 22:01 UTC, KPOTOH commented on homework_1/ml_project/models/utils.py
> +    }
Используемые метрики можно тоже в конфиг записать

2021-05-10 22:03 UTC, KPOTOH commented on homework_1/ml_project/train_pipeline.py
> +        transformer = load(f)
Можно вынести в отдельную функцию

2021-05-10 22:21 UTC, KPOTOH commented
Ошибки:
- данные надо куда-нибудь, но не в гитхаб

Улучшения:
- расширение конфига для более обширной настройки модели и получения желаемых метрик
- есть мнение, что конфиг для предикта лучше написать отдельный

Согласен с самооценкой:
22 балла.

2021-05-23 21:50 UTC, Sergey-Pravdyukov commented
Объясни пожалуйста по каким соображениям `data`, `entities`, `features`, `models` расположены в `./ml_project`, а `configs`, `notebooks`, `tests` - нет?

2021-05-23 21:55 UTC, Sergey-Pravdyukov commented
`.gitkeep` помещается в пустую директорию, в нахождении `.gitkeep` в `./ml_project/data` нет никакого смысла.

2021-05-23 21:58 UTC, Sergey-Pravdyukov commented on homework_1/data/raw/test.csv
> +age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
> Гитхаб не для данных (даже в игрушечном примере)

Проверяющим сильно приятнее когда данные все же есть :)

2021-05-23 21:59 UTC, Sergey-Pravdyukov commented on homework_1/ml_project/models/train_model.py
> +    return model
Согласен.

2021-05-23 21:59 UTC, Sergey-Pravdyukov commented on homework_1/ml_project/models/utils.py
> +    }
Согласен.

2021-05-23 22:04 UTC, Sergey-Pravdyukov requested changes
С комментариями @KPOTOH по большей части согласен, единственное - не удаляй датасет пожалуйста :)

Готов усовершенствовать свое решение?

2021-05-24 16:58 UTC, rchermanteev commented
> Объясни пожалуйста по каким соображениям `data`, `entities`, `features`, `models` расположены в `./ml_project`, а `configs`, `notebooks`, `tests` - нет.

Изначально я подразумевал ml_project как отдельное приложение внутри проекта, поэтому вынес информацию о конфигах, данных и тестах во вне. Но не уверен, что данный подход верный.

2021-05-24 17:00 UTC, rchermanteev commented
> `.gitkeep` помещается в пустую директорию, в нахождении `.gitkeep` в `./ml_project/data` нет никакого смысла.

Хорошо, буду знать.

2021-05-24 17:01 UTC, rchermanteev commented
> С комментариями @KPOTOH по большей части согласен, единственное - не удаляй датасет пожалуйста :)
> 
> Готов усовершенствовать свое решение?

Да, доработаю по замечаниям до конца недели

2021-05-30 14:43 UTC, rchermanteev commented
@Sergey-Pravdyukov Обновил код, с учётом замечаний

2021-05-31 19:32 UTC, Sergey-Pravdyukov approved these changes
Ок, 22 балла!

2021-06-03 16:04 UTC, merged