Homework2
made-ml-in-prod-2021/rchermanteev pull request #3
Opened 2021-05-19 16:33 UTC by rchermanteev

Здравствуйте!

В домашней работе был сделан REST сервис для получения предсказаний.
За основу была взята первая домашняя работа.
Работа выполнялась по пунктам из поста
В README приведён чек-лист по пунктам, он же является самоанализом моей работы.

2021-05-23 13:26 UTC, Mikhail-M requested changes
скопирован весь код первой дз, это как-то не очень, нужно добиться ситуации, что будет сдан на проверку только код из online_inference. 

Можно посмотреть как сделано у других по структуре

2021-05-30 15:00 UTC, rchermanteev commented
Здравствуйте! 
Немного поменял структуру проекта, посмотрев на другие работы.
Как добиться того, чтобы в этот pull request не попал код из первой дз, когда он ещё не слит и мне надо его использовать в дз2, я не понимаю :(

2021-06-09 14:42 UTC, rchermanteev commented
@Mikhail-M Здравствуйте, пулл-реквест уже долго висит без ответа, напоминаю о нём.

2021-06-13 10:32 UTC, Mikhail-M commented
> @Mikhail-M Здравствуйте, пулл-реквест уже долго висит без ответа, напоминаю о нём.

нужно возращать в работу, ваше напоминание в таком виде -- не работает

2021-06-13 10:32 UTC, Mikhail-M commented
![image](https://user-images.githubusercontent.com/5405304/121803798-d26e7580-cc4b-11eb-80a3-27b1a2f4a993.png)

2021-06-13 10:32 UTC, Mikhail-M commented
у вас конфликты

2021-06-13 10:33 UTC, Mikhail-M commented
я так понимаю, замечание исправить не получилось, ну хорошо.
проверю в таком виде

2021-06-13 13:21 UTC, rchermanteev commented
Конфликты появились после того, как замерджил первую дз. Решил пока не исправлять до вашего ответа. 
Я смотрел чужие реквесты, но не понял как это решается :(
Не знал про функционал возвращения работы, буду знать, спасибо

2021-06-18 15:16 UTC, Mikhail-M commented
у вас все еще конфликты

2021-06-18 15:19 UTC, Mikhail-M approved these changes
Оптимизация: 1.5
Валидация: 1.5
Тесты: 1.5

Смешан код обучения и использования модели: -2 балла
Конфликты: - 1 балл
Баллы: 22-1-2-1.5-1.5-1.5=14.5

2021-06-18 16:12 UTC, rchermanteev commented
Конфликты исправил. 
Спасибо за проверку.
Можете, пожалуйста, уточнить, что неправильно в тестах и валидации, чтобы я мог доработать?

2021-06-22 07:53 UTC, Mikhail-M reviewed
в валидации мало проверок, в тестах хорошо, чтобы
1) так же больше проверок
2) чтобы была возможность тестировать код, без наличия файла модели(мокать её ответы, либо готовить в фикстиру)

2021-06-23 08:19 UTC, merged