Homework4
made-ml-in-prod-2021/rchermanteev pull request #5
Opened 2021-06-13 11:55 UTC by rchermanteev

Здравствуйте!

Была выполнена домашняя работа по k8s.
За основу были взяты материалы семинара.
Работа выполнялась по пунктам из поста.
В README приведён чек-лист по пунктам, он же является самоанализом моей работы.

1) Развернул k8s локально. Пользовался https://kind.sigs.k8s.io/docs/user/quick-start/ проблем не вызвало
2) 
![image](https://user-images.githubusercontent.com/37110744/121805339-93dcb900-cc53-11eb-8516-36262512b2ec.png)
![image](https://user-images.githubusercontent.com/37110744/121805352-a48d2f00-cc53-11eb-9e47-666b0e2a22e2.png)
![image](https://user-images.githubusercontent.com/37110744/121805684-d0f57b00-cc54-11eb-8603-79a5dc40ede1.png)

2а) Выставление лимитов нужно для лучшей оркестрации контейнерами (оптимальнее расходуем ресурсы машин)
3) Добились того, что теперь мы понимаем когда наше приложение готово к работе и когда оно вышло из строя(перезапускаем его). Для знакомства с этими инструментами использовал образ из туториала k8s.
![image](https://user-images.githubusercontent.com/37110744/121805802-6abd2800-cc55-11eb-8873-48bf0cd43778.png)
![image](https://user-images.githubusercontent.com/37110744/121805819-8294ac00-cc55-11eb-99cf-753b5596573e.png)

4)
а) Если уменьшить число реплик, то replicaset убьёт лишние pod-ы, оставшиеся останутся старыми (ничего не обновится)
б) Если увеличить число реплик, то replicaset добавит новые pod-ы до установленного числа, при этом старые не поменяют свою версию, а новые создадутся с новым образом 
Стоит отметить, что если вручную удалить pod со старым образом, то создастся pod с новым образом. Так же стоит сказать, что  replicaset  никак не следит за версиями pod-ов, его главная задача поддерживать определённое число подов в работе.
![image](https://user-images.githubusercontent.com/37110744/121806018-a5739000-cc56-11eb-98f5-bb15c91f3a38.png)

5) Реализовал стратегию blue-green с помощью maxSurge: 100% и maxUnavailable: 0. Таким образом есть момент, когда работают и все pod-ы со старыми версиями и все pod-ы с новыми, после старые поды сворачиваются.

2021-06-13 14:52 UTC, Mikhail-M requested changes
В ревью код 3-го дз.

2021-06-13 16:07 UTC, rchermanteev commented
Я не знаю как избежать попадания кода из прошлых дз в ревью до проверки и мерджа предудущих дз. Просьба смотреть только код из папки kubernetes_hw, там hw4.

2021-06-18 15:19 UTC, Mikhail-M commented
нет, это должно быть исправлено, иначе я буду снижать баллы

2021-06-18 16:24 UTC, rchermanteev commented
Поправил, не уверен, что так правильно, но конфликтов не появилось.

2021-06-23 16:32 UTC, Mikhail-M approved these changes
Баллы: 20

2021-06-23 17:16 UTC, merged